// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2wTBxUMG_bZAyz73sPDaEqhdd9lr0_5Q',
    appId: '1:195200771117:web:e3b9550fc8258a4b3844a4',
    messagingSenderId: '195200771117',
    projectId: 'object-guesser',
    authDomain: 'object-guesser.firebaseapp.com',
    storageBucket: 'object-guesser.appspot.com',
    measurementId: 'G-946ZWKW6RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj1jEyt3AzTjuVk5TR4KK1AAGfbFBLaik',
    appId: '1:195200771117:android:2ab7c444f81c50213844a4',
    messagingSenderId: '195200771117',
    projectId: 'object-guesser',
    storageBucket: 'object-guesser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5gXlTgp5aepwafR2OTBHg4jd4ionMqY',
    appId: '1:195200771117:ios:24e91b35cbe1dd083844a4',
    messagingSenderId: '195200771117',
    projectId: 'object-guesser',
    storageBucket: 'object-guesser.appspot.com',
    iosClientId: '195200771117-psp5qr421p0ujevpmvcfm30m9il119hh.apps.googleusercontent.com',
    iosBundleId: 'com.example.objectGuesser',
  );
}
